### ISSUE TITLE
Instagram link doesn’t exist 

### ISSUE THREAD

**Issue by inuka91** [BragaAndrei/testing#101]
Description: Instagram link doesn’t exist (Firefox, Chrome)
Platform: Win10 64 bit/ Firefox 63.0.3 / (Chrome 70.0.3538.110) 
Steps to reproduce: 
1. Go to http://www.airport.md
2. On the main page click on the icon ‘Instagram’
Actual result:
Opening a new window of the site Instagram and appears the message:” You have used an invalid link or page has been deleted. Back to Instagram.”.
Expected result: 
Has been opened the page ‘airport.md’ on the website Instagram
Severity: Major
Priority: Medium
Screenshot attached (the defect): 
![image](https://user-images.githubusercontent.com/45799785/49870008-c73bf400-fe1a-11e8-901f-8dad39171cbb.png)
![image](https://user-images.githubusercontent.com/45799785/49870021-cd31d500-fe1a-11e8-9915-5144d0398c09.png)

**Comment by BragaAndrei** [comment]
Again Step**s!**!

**Comment by BragaAndrei** [comment]
Great work!

**Comment by inuka91** [comment]
Thank's Andrew,
I have already fixed everything👌



>Среда, 12 декабря 2018, 14:44 +02:00 от BragaAndrei <notifications@github.com>:
>
>Снова Step  s!  !
>- 
>Вы получаете это, потому что вы автор темы. 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  отключите тему .

невинный подонок
