### ISSUE TITLE
Video is not displayed when clicked on [Video-guide] button 

### ISSUE THREAD

**Issue by inuka91** [BragaAndrei/testing#102]
Description: Video is not displayed when clicked on [Video-guide] button (Firefox)
Platform: Win10 64 bit/ Firefox 63.0.3 / 
Steps to reproduce: 
1. Go to  http://www.airport.md
2. Click on the [Video-guide] button on the main page
Actual result:
Video doesn’t display.
Expected result:
The video is played in the video window.
Severity: Major
Priority: Medium
Screenshot attached (the defect): 
![image](https://user-images.githubusercontent.com/45799785/49870150-3a456a80-fe1b-11e8-958d-c1b87b60b304.png)

**Comment by BragaAndrei** [comment]
Step to reproduce - Step**s** to reproduce: because you have more than one step!

**Comment by BragaAndrei** [comment]
good work!
