### ISSUE TITLE
The weather is not shown on the site

### ISSUE THREAD

**Issue by Artur02111998** [BragaAndrei/testing#103]
**Description:** I go to website want to see the weather but it is not displayed.

 **Platform:** Win 10 Pro 32bit / Chrome Версия 70.0.3538.110

**Step to reproduce:**

### 2. click on "Meteo" button

**Actual result:**  The weather data is missing

**Expected result:** The displaying weather data

**Severity:** Medium
**Priority:** Medium

**Screenshot attached (the defect):** 
![screenshot_1](https://user-images.githubusercontent.com/45799823/49878498-628b9400-fe30-11e8-8ae7-c8bace3594d3.png)

![screenshot_2](https://user-images.githubusercontent.com/45799823/49878514-6ddebf80-fe30-11e8-9160-ad07711a971d.png)

**Comment by BragaAndrei** [comment]
good

**Comment by Artur02111998** [comment]
OK
