### ISSUE TITLE
Version of product 

### ISSUE THREAD

**Issue by vacari4444** [BragaAndrei/testing#15]
Platform: Win8.164 bit

**Step to reproduce:**:
1.Open ListBoxer.exe
2. Click button[Help]
3.Select from drop down list 'About ListBoxer...'

**Expected result:** According from "ListBoxer_requerments.doc" the version of product must to be '1,98'
**Actual result:** The version of product is '1,89'
**Severity:** high
**Priority:** high
![version](https://user-images.githubusercontent.com/43859348/46582437-54e01980-ca4f-11e8-9295-72f58e9932f8.jpg)

**Comment by BragaAndrei** [comment]
It's great that you paid attention
