### ISSUE TITLE
The program saves the file under an existing name without asking if we want to replace it.

### ISSUE THREAD

**Issue by mihai1994** [BragaAndrei/testing#159]
**Steps to reproduce:**
1. Open the "ListBoxer.exe"
2. Insert '1986' value
3. Click [Add to List] button
4. On the list box click "File"
5. On the appeared menu click "Save us"
6. On the appeared window insert the name of existing file
7. Click [Save] button
**Actual result:** File has been saved and replaced"
**Expected result:** A window will appear asking for the permission of replacement

Severity: High
Priority: Medium

**Comment by BragaAndrei** [comment]
I saw it ! GOOD
