### ISSUE TITLE
When we enter a wrong value  it not appear but is registered in Total Records

### ISSUE THREAD

**Issue by mihai1994** [BragaAndrei/testing#162]
**Steps to reproduce:**
1. Open the "ListBoxer.exe"
2. On the "check box" select 'Alphabetic'
3. On the "drop down range" select 'n-z'
4. Insert '134', '145', 245', '98' values
5. Click [Add to List] button

**Actual result:** Total Record shows us 4 values
**Expected result:** Total Record shows us 0 values

Severity: Medium
Priority: High
![apere dar nu se vede](https://user-images.githubusercontent.com/47896473/53417049-66fe2c80-39dd-11e9-906a-70c3efe76427.png)

**Comment by BragaAndrei** [comment]
Did you write every value separate ?
