### ISSUE TITLE
The title 'ListBoxer' of program not correspond with title when we save a file and in proprieties of file

### ISSUE THREAD

**Issue by mihai1994** [BragaAndrei/testing#165]
**Steps to reproduce:**
1. Open the "ListBoxer.exe"
2. On the "check box" select Numeric
3. On the "drop down range" select All
4. Insert '1','2','3','4', values
5. Click [Add to List] button
6. In the "Title Menu File" select  'Save us'

**Actual result:** The title not correspond
**Expected result:** The title correspond

Severity: Low
Priority: Medium
![nume](https://user-images.githubusercontent.com/47896473/53419931-754f4700-39e3-11e9-8328-51905f299c04.png)

**Comment by mihai1994** [comment]
maybe it's the same not a bug but ...

**Comment by BragaAndrei** [comment]
ok I  saw it.
