### ISSUE TITLE
Hotkey: Paste ,Ctrl +V, doesn't work

### ISSUE THREAD

**Issue by paladii** [BragaAndrei/testing#171]
**Steps to reproduce:**

1. open "ListBoxer"
2. introduce character ,,a,, in field [Add to list]
3. select character ,,a,, in field [Add to list]
4. right click on mouse and select ,Copy, from drop down
3. try hotkey combiation: Paste ,Ctrl +V,

 
**Actual result:** hotkey combiation: Paste ,Ctrl +V, doesn't work
**Expected result:** hotkey combiation: Paste ,Ctrl +X, must work
 
**Severity:** medium
**Priority:** high
 
**Enviroment:** Platform: Win10 Pro 64 bit

**Comment by BragaAndrei** [comment]
2\. introduce character ,,a,, in field [Add to list] - Introduce in feild "a" 
Next step: Click [Add to List] button
