### ISSUE TITLE
Range data doesn't match with requirement from (0 to 9999)

### ISSUE THREAD

**Issue by paladii** [BragaAndrei/testing#172]
**Steps to reproduce:**

1. open "ListBoxer"
2. check -> ,Numeric, from ,Simbols, options
2. go to ,Range, select from drop down list ,300-9999,
3. write numeric simbols ,,10000,, in fielt [Add to list] and press
4. the ,,10000,, symbols was accepted in the ,List,
![screenshot_4](https://user-images.githubusercontent.com/47896590/53516335-bbd09e80-3ad4-11e9-975f-e42138315946.png)

 
**Actual result:** the ,,10000,, symbols was accepted in the ,List,
**Expected result:** according to requirements the ,,10000,, symbols, can't be acceptet in the field
 
**Severity:** high
**Priority:** low
 
**Enviroment:** Platform: Win10 Pro 64 bit

**Comment by BragaAndrei** [comment]
fielt  -  field -  Cimp unde se scriu data intr-un singur rind! ))))

**Comment by BragaAndrei** [comment]
name of button in **[ ]**
