### ISSUE TITLE
Descending fuction doesn't work right

### ISSUE THREAD

**Issue by paladii** [BragaAndrei/testing#173]
**Steps to reproduce:**

1. open "ListBoxer"
2. go to ,Range, select from drop down list ,All,
3. check -> ,Numeric, from ,Simbols, options
4. write numeric simbols ,,100, 200, ..., 600,, in fielt [Add to list] and press
5. check -> ,Descending, from ,Sort Order, options
6. in the ,List, ,Descending, option not working properly
 
**Actual result:** the row from ,List, not working properly, with  ,Descending, option
**Expected result:** the function of  ,Descending, must work right
 
**Severity:** high
**Priority:** critical
![screenshot_5](https://user-images.githubusercontent.com/47896590/53520697-e9bae080-3ade-11e9-853c-3c6865a70645.png)

 
**Enviroment:** Platform: Win10 Pro 64 bit

**Comment by BragaAndrei** [comment]
I understood What you meant but steps are not right written
