### ISSUE TITLE
In [Edit] drop down list, 3 buttons are inactive

### ISSUE THREAD

**Issue by paladii** [BragaAndrei/testing#174]
**Steps to reproduce:**

1. open "ListBoxer"
2. go to ,Range, select from drop down list ,All,
4. write alphabetic simbol ,,a,, in fielt [Add to list] and press
5. click [Edit] buttton 
6. In [Edit], drop down list, the buttons: [Cut] [Copy] [Paste] are inactive
 
**Actual result:** from drop down [Edit], butons [Cut] [Copy] [Paste] are inactive
**Expected result:** from drop down [Edit], butons [Cut] [Copy] [Paste] must be active
 
**Severity:** high
**Priority:** medium
![screenshot_6](https://user-images.githubusercontent.com/47896590/53521875-e4ab6080-3ae1-11e9-9184-c3094721d61f.png)

 
**Enviroment:** Platform: Win10 Pro 64 bit

**Comment by BragaAndrei** [comment]
Step number 3 I did not understand
