### ISSUE TITLE
In the title bar is missing the [-] minimize button

### ISSUE THREAD

**Issue by paladii** [BragaAndrei/testing#175]
**Steps to reproduce:**

1. open "ListBoxer"
2. In the title bar is missing the [-] minimize button
 
**Actual result:** In the title bar is missing the [-] minimize button
**Expected result:** In the title bar must be the [-] minimize button
 
**Severity:** low
**Priority:** low
![screenshot_7](https://user-images.githubusercontent.com/47896590/53523023-60a6a800-3ae4-11e9-900e-f1c27028b603.png)

 
**Enviroment:** Platform: Win10 Pro 64 bit

**Comment by BragaAndrei** [comment]
It is not a bug but a ficha
