### ISSUE TITLE
Accessing the [Contents] button, is opening a webpage with error

### ISSUE THREAD

**Issue by paladii** [BragaAndrei/testing#176]
**Steps to reproduce:**

1. open "ListBoxer"
2. go to ,Help, button
3. from drop down select ,Contents,

**Actual result:** The [Contents] button open a webpage with error (Help not supported)
**Expected result:** The [Contents] button open an webpage wich must contain descriptions help
  
**Severity:** medium
**Priority:**  high

![screenshot_8](https://user-images.githubusercontent.com/47896590/53524257-9b5e0f80-3ae7-11e9-8cf5-a765b3f00b45.png)

 
**Enviroment:** Platform: Win10 Pro 64 bit

**Comment by BragaAndrei** [comment]
Great job Tatiana !!

**Comment by BragaAndrei** [comment]
Everything is correct!!
