### ISSUE TITLE
The last row on a "drop down range" is displayed incorrectly

### ISSUE THREAD

**Issue by mihai1994** [BragaAndrei/testing#177]
**Steps to reproduce:**
1. Open the "ListBoxer.exe"
2. On the "drop down range" select the last row
**Actual result:** The last row is empty
**Expected result:** The last row is missing

Severity: Medium
Priority: Medium
![loc liber](https://user-images.githubusercontent.com/47896473/53598556-c317ab00-3bad-11e9-866b-5198789667a6.png)

**Comment by BragaAndrei** [comment]
got it
