### ISSUE TITLE
In the description program not indicated correctly the input range

### ISSUE THREAD

**Issue by mihai1994** [BragaAndrei/testing#178]
**Steps to reproduce:**
1. Open the "ListBoxer.exe"
2. On the Menu Title click "Help"
3. On the list box click "Contents"
4. In the appeared window press [Display] button
   **Actual result:** input range from <a> to <z> and <A> to <Z>
   **Expected result:** input range from <a> to <m> and <n> to <z>

**Severity: Low** 
**Priority: Low**
![a-za-z](https://user-images.githubusercontent.com/47896473/53599018-e98a1600-3bae-11e9-9eb1-b294cacdded6.png)

**Comment by BragaAndrei** [comment]
Yes it is a bug! Lowet Priority :D
