### ISSUE TITLE
Canceling the installation of the program does not work correctly

### ISSUE THREAD

**Issue by mihai1994** [BragaAndrei/testing#179]
**Steps to reproduce:**
1. Open the "setup.exe"
2. In the opening "ListBoxer setup" window click the [Exit Setup] button
3. In the next opening "ListBoxer setup" window confirm the exiting and click the [OK] button
 **Actual result:** The setup.exe has been closed 
 **Expected result:** The setup.exe not closed and will appear a error window.

**Severity: Medium 
Priority: Medium**
![dezinstalare](https://user-images.githubusercontent.com/47896473/53599496-f9eec080-3baf-11e9-90d3-e01fc03875dc.png)

**Comment by BragaAndrei** [comment]
I would put Severity High and Priority High
