### ISSUE TITLE
Wrong descending numeric list 

### ISSUE THREAD

**Issue by vacari4444** [BragaAndrei/testing#18]
Platform: Win8.164 bit

**Step to reproduce:**
1.Open ListBoxer.exe
2.Tick "Numeric"
3.Introduce "1" in field in the top right
4.Click button [Add to list]
5.Introduce "2" in field in the top right
6.Click button [Add to list]
7.Introduce "3" in field in the top right
8.Click button [Add to list]
9.Introduce "4" in field in the top right
10.Click button [Add to list]
11.Introduce "5" in field in the top right
12.Click button [Add to list]
13.Click radiobutton"Descending" in  'Sort Order'

**Expected result:** "Descending" list sorted '5 4 3 2 1'
**Actual result:** "Descending" list is ' 5 4 3 1 2'

**Severity:** high
**Priority:** high
![descendent](https://user-images.githubusercontent.com/43859348/46583240-303e6e80-ca5c-11e8-860b-bbcab7151c9d.jpg)

**Comment by BragaAndrei** [comment]
good spot
