### ISSUE TITLE
The question mark from the title bar is not working

### ISSUE THREAD

**Issue by CristinaStinga** [BragaAndrei/testing#182]
Description:
The question mark in the title bar is not working.

Steps to Reproduce:
1.Open the program “List Boxer”;
2. Look at the title bar.

Expected result: It should be opening a window with some questions.
 

Severity: Low
Priority: Low
![5](https://user-images.githubusercontent.com/47896518/53603426-2b6c8980-3bba-11e9-9c42-054487290bb2.JPG)

**Comment by BragaAndrei** [comment]
Incorrect bug
