### ISSUE TITLE
The hot keys are inactive

### ISSUE THREAD

**Issue by CristinaStinga** [BragaAndrei/testing#183]
Description:
The hot keys like “ Copy Ctrl +C”, “ Cut Ctrl +X”, “ Paste Ctrl +V” don’t work.

Steps to Reproduce:
1.Open the program “List Boxer”;
2.Introduce some value;
3. Select the information that you want to copy, cut or paste;
4. Press on “Edit” menu and select or select hot keys.

Expected result: It should be execute the  operations.
 

Severity: High
Priority: High
![6](https://user-images.githubusercontent.com/47896518/53604358-e564f500-3bbc-11e9-89cd-906994ff7d20.JPG)

**Comment by BragaAndrei** [comment]
Actual result ?

**Comment by BragaAndrei** [comment]
Assign ? project ? label?
