### ISSUE TITLE
The number string is not written correctly in the “Range” scroll bar.

### ISSUE THREAD

**Issue by CristinaStinga** [BragaAndrei/testing#184]
Description:
The number string from ‘300-9999’ is not written correctly in the “Range” scroll bar.

Steps to Reproduce:
1.Open the program “List Boxer”;
2. Select from drop down “Range” the string numbers’300-9999’.

Expected result: It should be organize the strings from ‘301-9999’.
 

Severity: Medium
Priority: Medium
![7](https://user-images.githubusercontent.com/47896518/53604807-34f7f080-3bbe-11e9-96a5-6f9b6cabb1c4.JPG)

**Comment by BragaAndrei** [comment]
Why did you put for every bug  the same Severity and Priority ?
