### ISSUE TITLE
The program permits to introduce a number bigger than 9999.

### ISSUE THREAD

**Issue by CristinaStinga** [BragaAndrei/testing#185]
Description:
The program permit to introduce a number bigger than 9999, although the string numbers is restricted till the 9999.

Steps to Reproduce:
1.Open the program “List Boxer”;
2. Introduce some value;.
3. Introduce ‘10000’;
4.Write’10003’;

Expected result: It must to decline this records.
 

Severity: Medium
Priority: Medium
![8](https://user-images.githubusercontent.com/47896518/53605278-af754000-3bbf-11e9-8715-88e7840dcea2.JPG)

**Comment by BragaAndrei** [comment]
Again Project and Label were not selected

**Comment by BragaAndrei** [comment]
Where is actual result!?
