### ISSUE TITLE
The first record can’t be deleted.

### ISSUE THREAD

**Issue by CristinaStinga** [BragaAndrei/testing#186]
Description:
After inserting a value, it can’t be erased by”Clear List”.

Steps to Reproduce:
1.Open the program “List Boxer”;
2. Introduce a value;.
3. Click the button”Clear List”

Expected result: It must to delete the record.
Severity: Medium
Priority: Medium
![9](https://user-images.githubusercontent.com/47896518/53622517-b70a0880-3c02-11e9-942e-c4eef1b96499.JPG)

**Comment by BragaAndrei** [comment]
name of button is necessary to put in **[ ]**

**Comment by BragaAndrei** [comment]
Where is actual result ?

**Comment by BragaAndrei** [comment]
Project did not selected

**Comment by BragaAndrei** [comment]
Any label selected!! why?
