### ISSUE TITLE
Airport website button "Meteo" no result

### ISSUE THREAD

**Issue by mcracea** [BragaAndrei/testing#198]
Platform:   Chrome Version 73.0.3683.86 (Official Build) (64-bit)

Step to reproduce: 
1. Open page http://www.airport.md/homepage-ro/
2. Click "Meteo" on homepage 

Actual Result: in opened page no information
![BugMeteo](https://user-images.githubusercontent.com/49408973/55743232-7344c300-5a3a-11e9-998c-5b57a1816401.JPG)

Exetped result: Show weather.
Security: Low 
Priority: 2

**Comment by BragaAndrei** [comment]
it is good
bug would be better without "nui nimic"
