### ISSUE TITLE
The email is not admissible

### ISSUE THREAD

**Issue by zikus1** [BragaAndrei/testing#2]
1. Go to www.airport.md
    2. Click on [Address your question] button 
    3. Insert name 'andrei'
    4. Insert email 'a@..ru'
    5. Insert your quation
    6. Insert Code
    7. Click on [Adress you quation] button 

Expected result:
The data sent (Coment:’the email is not admissible’)

Actual Result:
Message has been sent

**Comment by BragaAndrei** [comment]
good find
