### ISSUE TITLE
Vamal service on MD version

### ISSUE THREAD

**Issue by oxxany123** [BragaAndrei/testing#201]
**Bug.003**
**Title** :   Vamal service on MD version  on the web site  airport.md.
 Has been verified on  **Fire Fox**  Platform.
**Steps to reproduce:** 
1. Navigate on  www.airport.md  web site
2. Click on    ”**Adresati  intrebarea dvs.**”
3. Open **“Intrebari privind bunurile si valuta transporta**te”
4.Click on **Serviciul Vamal**
**Actual Results:**
  This service opening in EN. version.
**Screenshot attached :**

![image](https://user-images.githubusercontent.com/49409250/55800502-8d36e200-5adc-11e9-88b7-34b5e0b35aab.png)
![image](https://user-images.githubusercontent.com/49409250/55800523-94f68680-5adc-11e9-9dc7-c5e268b442ed.png)

**Expected Results:**   It should be opened in MD.version
**Severity:** Major
**Priority**: Hight

**Comment by BragaAndrei** [comment]
priority in digits please

**Comment by BragaAndrei** [comment]
it's not necessary to write everytime Bug.003 or ever

**Comment by BragaAndrei** [comment]
![image](https://user-images.githubusercontent.com/43719014/55906721-9491e480-5bdd-11e9-9f70-63afe6ac2b66.png)
