### ISSUE TITLE
Meteo is not available on web site

### ISSUE THREAD

**Issue by oxxany123** [BragaAndrei/testing#202]
**Bug.004**
**Title** : Meteo is not available  on the web site www.airport.md.
 Has been verified on  **Internet Explorer ,Fire Fox** Platform.
**Steps to reproduce:** 
1. Navigate on  www.airport.md  web site
2. Click on **Chisinau”**
**Actual Results:**
  This service are not meet requirements.
**Screenshot:**
**Explorer**
![image](https://user-images.githubusercontent.com/49409250/55801192-30d4c200-5ade-11e9-97f1-9142c400646d.png)
**Fire Fox**
![image](https://user-images.githubusercontent.com/49409250/55801328-7ee9c580-5ade-11e9-8223-a3324340e5cb.png)

**Expected Results:**   It should be opened the meteo.
**Severity:** Major
**Priority**: Hight

**Comment by BragaAndrei** [comment]
Severity: High or Medium
Priority: 2
