### ISSUE TITLE
Video Gallery is not available

### ISSUE THREAD

**Issue by oxxany123** [BragaAndrei/testing#203]
**Bug.005**
**Title :** Video Gallery is not available on  platforms  on web site www. airport.md.
 Has been verified on  **Fire Fox, Google ,Internet Explorer**  Platforms.
Steps to reproduce: 
1. Navigate on  www.airport.md  web site
2. Click on    **”Business  information**”
3. Open **“About us”**
4.Click on **“Video Gallery”**
**Actual Results:**
  Video Gallery  is not meet requirements  on **Fire Fox, Google** platforms but is available on **Internet Explorer** .
**Screenshot:**
**Fire Fox**
![image](https://user-images.githubusercontent.com/49409250/55801898-bdcc4b00-5adf-11e9-87e4-eaab7c62eadf.png)
**Google**
![image](https://user-images.githubusercontent.com/49409250/55801922-d177b180-5adf-11e9-8164-c74bc43490d6.png)
 **Internet Explorer**
![image](https://user-images.githubusercontent.com/49409250/55801964-e8b69f00-5adf-11e9-99c1-3b29f7e3a901.png)

**Expected Results:**   Video should be opened in all platforms.
**Severity**: Minor
**Priority:** Major

**Comment by BragaAndrei** [comment]
here you needed to raise a bug just for the platform where video does not playing
