### ISSUE TITLE
Duplicated city names displayed in drop down "Cautarea Curselor"

### ISSUE THREAD

**Issue by ecotaga** [BragaAndrei/testing#204]
**Description**: look for airport in a City destination (e.g. Parma), found 2 Cities with the same name, airport abbreviation not mentioned. 
**Platform**: Win10 64 bit/ Firefox, Safari
**Steps to reproduce**:
1	Open web site www.airport.md
2	Main page
3	Navigate through page
4	Access ‘Cautarea curselor’ -> Alegeti o destinatie -> Parma

**Actual result**: Seen Parma twice, no abbreviation for airport according to standards
**Expected result**: by clicking on ‘Alegeti o destinatie’ find Parma (PMF)

**Severity**: Low
**Priority**: 2

**Comment by BragaAndrei** [comment]
in this case will be better to set up Priority 2
and please select your project

**Comment by BragaAndrei** [comment]
![image](https://user-images.githubusercontent.com/43719014/55906433-eede7580-5bdc-11e9-8bb6-48ffb432e20d.png)
