### ISSUE TITLE
First page defect of not opening the e-mail address of hotline

### ISSUE THREAD

**Issue by NataliaCrigan** [BragaAndrei/testing#205]
**Description**: Finding bugs on the web-page airport.md. Issue is reproducible in Chrome
**Platform**: Chrome (Chrome Версия 54.0.2840.87 m)
**Steps to reproduce**:
1.	Log on airport.md web page
2.	Navigate on site
4.	Click on email address on first page upper left corner “hotline@airport.md” 
5. 	By clicking on the e-mail address, it’s not opening the email page to be able to write an e-mail

**Actual result**: Request processing failed: 
**Expected result**: E-mail address is not responding to be able to open and write to hotline of the organization.
**Severity:** 1
**Priority**:high

Screenshot attached (the defect) :     
![image](https://user-images.githubusercontent.com/49408896/55894911-d01fb500-5bc3-11e9-91b7-cb6fec386126.png)

**Comment by BragaAndrei** [comment]
great job!!!
