### ISSUE TITLE
E-mail address for hotline is missing on the first page

### ISSUE THREAD

**Issue by NataliaCrigan** [BragaAndrei/testing#206]
**Description**: Issue is reproducible in the internet explorer
**Platform**: Internet Explorer
**Steps to reproduce:**
1.	Open web page airport.md 
2.	Navigate on site
4.	On the first page upper left corner the e-mail address hotline@airport.md is missing, not displayed

**Actual result**: Request processing failed
**Expected result**: By looking on the first page you cannot find the e-mail address for hotline of the organization, it’s not displayed 
**Severity**: 1
**Priority**: high
Screenshot attached (the defect): 
![image](https://user-images.githubusercontent.com/49408896/55898049-779fe600-5bca-11e9-9af0-f982048bebb0.png)

**Comment by BragaAndrei** [comment]
it is not necessary to write it "Description: Issue is reproducible in the internet explorer"

**Comment by BragaAndrei** [comment]
it's not correct to set up Priority: high it this case will be better to put severity Low because absent of email address does not influence so much on functional part
