### ISSUE TITLE
Incorrect name version 

### ISSUE THREAD

**Issue by anastiu6a** [BragaAndrei/testing#22]
Platform: Win7 64 bit
Step to reproduce:
     1. Open ListBoxer 
     2.Select from drop down "Help" 'Abolut ListBoxer'
Actual result: List Boxer Version 1.89
Expected result: List Boxer Version 1.98
Severity: Low
Priority: 1
![versia](https://user-images.githubusercontent.com/43859330/46586613-b1602a80-ca89-11e8-8e93-496b7a6cc42e.jpg)

**Comment by BragaAndrei** [comment]
good ! but you did not assign this bug
