### ISSUE TITLE
Negative symbols added to list (Numeric)

### ISSUE THREAD

**Issue by anastiu6a** [BragaAndrei/testing#23]
Platform: Win7 64 bit
Step to reproduce:
     1. Open ListBoxer 
     2.Select from drop down "Range" 'All'
     3.Select from check box "Symbols" 'Numeric'
     4. Introduce in field '10000'
     5. Click button [Add to list]
Actual result: '10000' added to list
Expected result: '10000' is not added to the list
Severity: Medium
![10000](https://user-images.githubusercontent.com/43859330/46586661-61ce2e80-ca8a-11e8-8ea5-08639068e887.jpg)

Priority: 2

**Comment by anastiu6a** [comment]
У меня не получается редактировать. в степы один шаг пропустила - Select from chekbox "Symbols" 'Numeric'

**Comment by anastiu6a** [comment]
И на счет Severity: 4 - я думаю что все таки должно быть значение 3

**Comment by BragaAndrei** [comment]
you did not assign this bug
