### ISSUE TITLE
Incorrect work Sort Order - Descending(Numeric)

### ISSUE THREAD

**Issue by anastiu6a** [BragaAndrei/testing#25]
Platform: Win7 64 bit
Step to reproduce:
     1. Open ListBoxer 
     2.Select from drop down "Range" 'All'
     3. Select from radiobutton "Sort Order" 'Descending'
     4. Select from checkbox "Symbols" 'Numeric'
     5. Introduce in field symbols from '1' to '5', after every symbol Click button [Add to list]
     
Actual result: 5,4,3,1,2
Expected result: 5,4,3,2,1
Severity: Medium
Priority: 2

**Comment by BragaAndrei** [comment]
It's great that you paid attention
