### ISSUE TITLE
Hotkeys : Ctrl +V (Paste)

### ISSUE THREAD

**Issue by vacari4444** [BragaAndrei/testing#30]
**Platform: Win8.164 bit**

**Step to reproduce:**
1.Open ListBoxer.exe
2.Tick "Alphabetic"
3.Introduce "a" in field in the top right
4.Click button [Add to list]
5.Introduce "b" in field in the top right
6.Click button [Add to list]
7.Introduce "c" in field in the top right
8.Click button [Add to list]
9.Introduce "d" in field in the top right
10.Click button [Add to list]
11.Introduce "e" in field in the top right
12.Click button [Add to list]
13. Go to www.gitHub.com
14. Copy letter "c" from this page 
15. Go to ListBoxer.exe
16. Press "CTRL+V" on keybord in filed  in the top right

**Expected result**: Letter "c" has been passed in the field
**Actual result**: Hotkey don't work .

Severity: high
Priority: moderate

**Comment by BragaAndrei** [comment]
no bad
