### ISSUE TITLE
Function Copy from Menu

### ISSUE THREAD

**Issue by vacari4444** [BragaAndrei/testing#32]
**Platform: Win8.164 bit**

**Step to reproduce:**
1.Open ListBoxer.exe
2.Tick "Alphabetic"
3.Introduce "a" in field in the top right
4.Click button [Add to list]
5.Introduce "b" in field in the top right
6.Click button [Add to list]
7.Introduce "c" in field in the top right
8.Click button [Add to list]
9.Introduce "d" in field in the top right
10.Click button [Add to list]
11.Select a "c" from 'list'
12.Click "Edjt" from 'menu'
13. Select "Copy" from drop down list

**Expected result:** Letter "c" it had to be copied
**Actual result:** The function don't work

**Severity**: high
**Priority**: moderate
![function copy](https://user-images.githubusercontent.com/43859348/46629331-2b0b1d80-cb49-11e8-99e8-6af2f6da2a23.jpg)

**Comment by BragaAndrei** [comment]
Severity Critical
