### ISSUE TITLE
Function Paste from Menu

### ISSUE THREAD

**Issue by vacari4444** [BragaAndrei/testing#33]
**Platform: Win8.164 bit**

**Step to reproduce:**
1.Open ListBoxer.exe
2.Tick "Alphabetic"
3.Introduce "a" in field in the top right
4.Click button [Add to list]
5.Introduce "b" in field in the top right
6.Click button [Add to list]
7.Introduce "c" in field in the top right
8.Click button [Add to list]
9.Introduce "d" in field in the top right
10.Click button [Add to list]
11. Go to www.github.com
12. Copy letter "c" from this page
13. Go to ListBoxer.exe
14.Click "Edjt" from 'menu'
15. Select "Paste" from drop down list in the field in the top right

**Expected result**: Letter "c" has been passed in the field
**Actual result:** Function "Paste" don't work 

**Severity:** high
**Priority:** moderate
![function paste](https://user-images.githubusercontent.com/43859348/46629633-3ca0f500-cb4a-11e8-966d-cae75e100e9c.jpg)

**Comment by BragaAndrei** [comment]
Click **[Add to list]** button
