### ISSUE TITLE
Hotkeys : F1 (Content menu)

### ISSUE THREAD

**Issue by vacari4444** [BragaAndrei/testing#34]
**Platform: Win8.164 bit**

**Step to reproduce:**
1.Open ListBoxer.exe
2.Click "F1" on the 'keyboard'

**Expected result:** The document must to open and can be read.
**Actual result:** "Contents" for this version of Windows can't be find

**Severity:** Moderate
**Priority**: Medium
![contents](https://user-images.githubusercontent.com/43859348/46630012-8b02c380-cb4b-11e8-8069-7e3b6d114d9b.jpg)

**Comment by BragaAndrei** [comment]
Instead of Open use "Run"

**Comment by BragaAndrei** [comment]
Severity LOW
