### ISSUE TITLE
Video-Guide is not working on Linux

### ISSUE THREAD

**Issue by denis0368** [BragaAndrei/testing#4]
1. Go to site airport.md
2. go to Video-Guide
3. Press to Video-Guide
Expected Result: Should be appear the video with airport.
Actual Result: The window with video is empty
![2018-09-30 13-57-16](https://user-images.githubusercontent.com/43721386/46256823-d74d6400-c4b8-11e8-82a7-39a488d96927.png)

**Comment by BragaAndrei** [comment]
It's great that you paid attention
