### ISSUE TITLE
After clicking the [Close] button in the "Save ListBoxer File" application closes

### ISSUE THREAD

**Issue by GheorgheTI** [BragaAndrei/testing#402]
Platform: Win7 64 bit
Steps to reproduce:
1.	Open the ListBoxer application
2.	Select “All” from dropdown “Range” 
3.	Write in the field some data in front of [Add to List] button
4.	Click on [Add to List] button
5.	Select from dropdown ‘File” ->’Exit’
6.	Click on [Close] button

Actual result:
The application closes after pressing the [Close] button in the "Save ListBoxer List" window

![Screenshot_1](https://user-images.githubusercontent.com/66551725/84075500-efd78680-a9dc-11ea-8c46-72d6411fc990.png)
![Screenshot_2](https://user-images.githubusercontent.com/66551725/84075515-f6fe9480-a9dc-11ea-81a9-c7532a3a2410.png) ->
![Screenshot_3](https://user-images.githubusercontent.com/66551725/84075549-0382ed00-a9dd-11ea-941b-8c451186dfa8.png)

Expected result:
The application remains open
Severity: High
Priority: 1

**Comment by BragaAndrei** [comment]
Good one
