### ISSUE TITLE
on mobile version menu item is not displayed correct

### ISSUE THREAD

**Issue by Irina1A1** [BragaAndrei/testing#43]
1. open home page
2. open mobile version
3. click on “Поиск рейсов”
**Actual result:**
droop down “назначение”is shorten than others
**Expected result:**
droop down “назначение” should be the same width like others
**Severity:** Moderate
![bbbbb](https://user-images.githubusercontent.com/44743627/47962469-ca76df80-e025-11e8-8fdc-6276c34dbcc7.png)

**Comment by BragaAndrei** [comment]
hei :))
Priority??

**Comment by Irina1A1** [comment]
Hei :)))
Priority is low ))

вт, 6 нояб. 2018 г. в 21:09, BragaAndrei <notifications@github.com>:
