### ISSUE TITLE
the block “альтернативный контент” intersects with news block

### ISSUE THREAD

**Issue by ignatovaolga** [BragaAndrei/testing#47]
1. open home page
2. scroll dawn to the news block
3. see that block” альтернативный контент” intersect with news block
Actual result:the block “альтернативный контент” intersects with news block
Expected result: the news block should be displayed under the block ” альтернативный контент”
Severity: Moderate
Priority: Medium
![jhjngjhnj](https://user-images.githubusercontent.com/44743585/47962497-25103b80-e026-11e8-912c-e18d113b760e.png)

**Comment by BragaAndrei** [comment]
**1.**open home page
**2.**scroll dawn to the news block
**3.**see that block” альтернативный контент” intersect with news block
![image](https://user-images.githubusercontent.com/43719014/48087833-69abfa80-e211-11e8-89bc-f473950e5e3a.png)

**Actual result**:the block “альтернативный контент” intersects with news block
**Expected result:** the news block should be displayed under the block ” альтернативный контент”
**Severity:** Low
**Priority:** High
