### ISSUE TITLE
mismatching currency converter and actual date

### ISSUE THREAD

**Issue by tatoshka2018** [BragaAndrei/testing#49]
![bug2](https://user-images.githubusercontent.com/44743407/47962571-7e2c9f00-e027-11e8-803b-d5c9633bc952.png)

    1. Log in airport.md site
    2. Navigate Home Page
    3. Click on currency converter on bottom right corner
    4. Fill the data “100” in field “Eur”

Actual result: the data of currency refers to the date of February,5,2018

Expected result: the data must match actual date
Platform: Win7 64 bit/ Firefox 63.0.1 (64-бит) / (Chrome Версия 70.0.3538.77)
Severity: Moderate
Priority: High
Screenshot attached (the defect):

**Comment by BragaAndrei** [comment]
**1.** Go to  airport.md site
**2.** Navigate Home Page
**3.** Click on currency converter on bottom right corner
**4.** Fill the data “100” in field “Eur”
**Platform:** Win7 64 bit/ Firefox 63.0.1 (64-бит) / (Chrome Версия 70.0.3538.77)
![image](https://user-images.githubusercontent.com/43719014/48087635-eb4f5880-e210-11e8-80d5-7553d8048d6c.png)
**Expected result**: the data must match actual date
**Actual Result** where is ???
**Severity:** Moderate
**Priority:** High
