### ISSUE TITLE
Web site is not translating a full of 100% text

### ISSUE THREAD

**Issue by DinuSirbu** [BragaAndrei/testing#640]
**Steps to reproduce :**

**1.** Acces airport.md web site

**2.** Click on the drop down "Pentru pasageri" on top right corner 

Move mouse to hover "Informartii pentru pasageri "

Click "Importul si exportul de bunuri" 

Scroll down till gadgets and select EN language on top right corner

**Actual Result :**

The page is not correct translated

**Expected result** : The page should be fully translated 

**Environment**
Win 7 64bit/Chrome Версия 95.0.4638.69 (Официальная сборка), (64 бит)

**Priority** : 3
**Severity** : Low

![image](https://user-images.githubusercontent.com/94281472/141671480-d6d5052a-44d6-4def-8d21-5fb44d120fed.png)

**Comment by BragaAndrei** [comment]
@DinuSirbu could you please add priority and severity
