### ISSUE TITLE
The сontext help does not work for each control element

### ISSUE THREAD

**Issue by Dima12A** [BragaAndrei/testing#67]
Steps to reproduce:
1. Click on [?] 
2. Click on any control element

Actual result:
The сontext help does not work for each control element and opens "Windows support" web page
Expected result: 
Open coresponding help
Severity: Low

**Comment by Dima12A** [comment]
![screenshot_1](https://user-images.githubusercontent.com/44743358/48157242-cb369c80-e2d7-11e8-9035-ecb0607d6ba8.jpg)

**Comment by Dima12A** [comment]
don`t support video files (

**Comment by BragaAndrei** [comment]
I got it!
