### ISSUE TITLE
English version of website is not filled correctly

### ISSUE THREAD

**Issue by tatoshka2018** [BragaAndrei/testing#68]
**Step to reproduce:**

1. Log in airport.md site
2. Navigate Home Page
3. Click on [EN]
4. Choose from drop down "Services" 'Other Services in the Airport Terminal'
5. Choose from the list "Insurance service"

**Actual result:** The information about location and program of work is written in Romanian

**Expected result**: All information is written in English

**Platform:** Win7 64 bit/ Firefox 63.0.1 (64-бит) / (Chrome Версия 70.0.3538.77)
**Severity:** Moderate
**Priority:** High

Screenshot attached (the defect):
![bug5](https://user-images.githubusercontent.com/44743407/48221832-c3d8c700-e39b-11e8-9aba-b32cf2a85fae.png)

**Comment by BragaAndrei** [comment]
Great work !!! continue the same !!
