### ISSUE TITLE
The lack of button for rolling up program

### ISSUE THREAD

**Issue by tatoshka2018** [BragaAndrei/testing#70]
**Step to reproduce:**
1. Open the program Listboxer
2. Try to roll up the program

**Actual result**: the button for rolling up program is absent

**Expected result:** there is button for rolling up program
**Platform:** Win7 64 bit/ Firefox 63.0.1 (64-бит) / (Chrome Версия 70.0.3538.77)
**Severity:** High
**Priority:** High
Screenshot attached (the defect):

**Comment by BragaAndrei** [comment]
I saw this bug in jira (Y)
