### ISSUE TITLE
The desdending function works incorrectly

### ISSUE THREAD

**Issue by tatoshka2018** [BragaAndrei/testing#71]
**Step to reproduce:**
1. Open the program Listboxer
2. Choose range "a-m"
3. Write the word "apple"
4. Push [Enter]
5. Write the word "boy"
6. Push [Enter]
7. Write the word "girl"
8. Push [Enter]
9. Write the word "smile"
10. Push [Enter]
11. Choose desdending function

**Actual result:** the word "boy" is behind the word "apple"
*Expected result: * words correspond desdending alphabetic order
**Platform:** Win7 64 bit/ Firefox 63.0.1 (64-бит) / (Chrome Версия 70.0.3538.77)
*Severity: * High
**Priority:** High
![bug7](https://user-images.githubusercontent.com/44743407/48223120-f932e400-e39e-11e8-9c40-cef921fa854e.png)

**Comment by BragaAndrei** [comment]
![image](https://user-images.githubusercontent.com/43719014/48250838-5e6eef80-e408-11e8-8f6c-f0474e5c04e9.png)

**Comment by tatoshka2018** [comment]
I have corrected mistakes. Thanks for help!
