### ISSUE TITLE
Non-active link of website of Embassy of Ukraine

### ISSUE THREAD

**Issue by tatoshka2018** [BragaAndrei/testing#74]
**Step to reproduce:**

    1. Log in airport.md site
    2. Navigate Home Page
    3. Click on [RU]
    4. Choose from drop down "Information for passengers" -> 'Travel documents'
    5. In the list of "Embassies and Consular Missions in the Republic of Moldova" select
    'Embassy of Ukraine'.
    6. Click on link of web:  http://www.ambasua.md/

**Actual result**: the link does not work correct

**Expected result**: link works correct

**Platform:** Win7 64 bit/ Firefox 63.0.1 (64-бит) / (Chrome Версия 70.0.3538.77)

**Severity:** Moderate
**Priority:** Medium
![01](https://user-images.githubusercontent.com/44743407/48279638-d74a6780-e459-11e8-9cf6-1f7881992395.png)
![02](https://user-images.githubusercontent.com/44743407/48279641-db768500-e459-11e8-8e07-2f6515cf1bde.png)

**Comment by BragaAndrei** [comment]
I got it.
