### ISSUE TITLE
wrong translation on site https://bigshop.md/ru

### ISSUE THREAD

**Issue by Irina1A1** [BragaAndrei/testing#79]
**Steps :**
1. Open Chrome browser
2.Open site "https://bigshop.md/ru"
3. Choose  "language"->'RU' 
**Actual result:**
does not translate the entire site into the selected language
**Expected result:** 
must translate the entire site into the selected language
**Priority:** 2
**Severity:**low
![bigshop md - google chrome](https://user-images.githubusercontent.com/44743627/49080254-b8b2e180-f24b-11e8-8ee1-88966475217b.jpg)

**Comment by BragaAndrei** [comment]
I didn't understand at the beginning xD
Then I understood. but anyway it's your mistake Irina because you did not insert one step!!!
1Open Chrome browser
2.Open site "https://bigshop.md/ru"
3.Choose "language"->'RU'
-> **4.Scroll down the page**  <-
