### ISSUE TITLE
Information from a previously saved file is not fully displayed in applications

### ISSUE THREAD

**Issue by CorinaKarry** [BragaAndrei/testing#798]
Open ListBoxer

Click on drop down “Range”

Click on “All”

Click on check box “Ascending”

Click on check box “ Alphabetic”

Click on check box “Numeric”

Insert in filed “1a”

Click on button [Add to list]

Insert in filed “2b”

Click on button [Add to list]

Insert in filed “3c”

Click on button [Add to list]

Insert in filed “4d”

Click on button [Add to list]

Insert in filed “5e”

Click on button [Add to list]

Insert in filed “6f”

Click on button [Add to list]

Insert in filed “7g”

Click on button [Add to list]

Insert in filed “8h”

Click on button [Add to list]

Click on buttoh [File]

Click on “Save as”

Give a name to the file

Click on button [Save]

Click on button [Clear list]

Click on buttoh [File]

Click on “Open”

Select a previously saved file

Click on button [Open]

Actual result: Information from a previously saved file is not fully displayed in applications, part of the information is missing - “1a”.

Expected result: Information is fully displayed in applications.

Priority: 1
Severity: High

Среда
Win10 64 bit

![Без имени4](https://user-images.githubusercontent.com/116482452/197379530-9e9823f5-a568-4021-8526-7d167577f3c3.png)

![Без имени5](https://user-images.githubusercontent.com/116482452/197379538-6f8adf83-4273-4718-b135-64360bf7a86b.png)

**Comment by BragaAndrei** [comment]
I fixed the issue, @CorinaKarry  could you please retest the bug
