### ISSUE TITLE
the "block"-> [Jivochat] run into the [YouTube] icon

### ISSUE THREAD

**Issue by Irina1A1** [BragaAndrei/testing#80]
**Steps :**
1.Open Chrome browser
2.Open site "https://bigshop.md/ru"
3.Scrolling to the end of the page
**Actual result:**
the "block"-> [Jivochat] run into the [YouTube] icon
**Expected result:**
the "block"-> [Jivochat] does not have to run into the [YouTube] icon
**Priority:** Critical
**Severity:** High
 
![1 bigshop md - google chrome](https://user-images.githubusercontent.com/44743627/49082013-3decc500-f251-11e8-9dd5-c1890106342b.jpg)

**Comment by BragaAndrei** [comment]
xa xa xa it's not a bug :D
![image](https://user-images.githubusercontent.com/43719014/49103435-6a720280-f28c-11e8-85cc-e3847edb128a.png)

**Comment by BragaAndrei** [comment]
this bug depend on size of screen

**Comment by BragaAndrei** [comment]
**Priority**: Critical **Severity**: High are not correct!!!
