### ISSUE TITLE
 description is displayed with an offset

### ISSUE THREAD

**Issue by Irina1A1** [BragaAndrei/testing#81]
**Steps :**
1.Open Chrome browser
2.Open site "https://bigshop.md/ru"
3.Мouse over to the product
**Actual result:**
hovering over the product, the description is displayed with an offset
**Expected result:**
description should not be shifted
**Priority:** Critical
**Severity:** High
![4 bigshop md - google chrome](https://user-images.githubusercontent.com/44743627/49083912-b1dd9c00-f256-11e8-919b-338dd0cd0247.jpg)

**Comment by BragaAndrei** [comment]
Priority: Critical Severity: High are not right!!
here are Priority: Critical Severity: 1

**Comment by BragaAndrei** [comment]
For some products data about product is displaying correct
![image](https://user-images.githubusercontent.com/43719014/49103727-2d5a4000-f28d-11e8-838a-425f745fa21e.png)

**Comment by BragaAndrei** [comment]
![image](https://user-images.githubusercontent.com/43719014/49103763-44992d80-f28d-11e8-9a98-523abd3b7dc3.png)
