### ISSUE TITLE
 the description "Mobile phones" jumps

### ISSUE THREAD

**Issue by Irina1A1** [BragaAndrei/testing#82]
**Steps :**
1.Open Chrome browser
2.Open site "https://bigshop.md/ru"
3.Choose "Electronics" -> 'Phones and accessories' ->'Cell phones'
**Actual result:**
When updating the page, the description "Mobile phones" jumps
**Expected result:**
when updating the page, the description "Mobile phones" should not skip
**Priority:** low
**Severity:** High

**Comment by BragaAndrei** [comment]
Could you please send me the screenshot!?

**Comment by BragaAndrei** [comment]
oo sorry a got the video
