### ISSUE TITLE
"Passengers' video guide" only in English version

### ISSUE THREAD

**Issue by Tmborsikadu** [BragaAndrei/testing#85]
**Description:**  When I choose English language I can see in information for passengers “Passengers’ video guide”. But it isn’t in Romanian or Russian language. 
**Platform:** Windows 10 64 bit/ Chrome 70.0.3538.110
**Step to reproduce:**
1.	Go to website airport.md
2.	Click on ” Information for passengers”
3.	Scroll down
4.	Choose English language
5.	Click on “Passengers’ video guide”
6.	Choose Romanian

**Actual result:** It’s shown “Error 403 access denied”
**Expected result:**  It must be seen video guide for passengers in the chosen language.
**Severity:**  High
**Priority:** 2
**Screenshot attached (the defect):**
![image](https://user-images.githubusercontent.com/34817696/49835796-016cad80-fda9-11e8-9dc5-34121a7fb9a5.png)

![image](https://user-images.githubusercontent.com/34817696/49835801-07628e80-fda9-11e8-8d91-fabf6bd988c2.png)

**Comment by BragaAndrei** [comment]
**Severity**: Low, Medium, High, Critical 
**Priority**: 1, 2, 3, 4

**Comment by BragaAndrei** [comment]
great work!

**Comment by BragaAndrei** [comment]
wonderful design of bug

**Comment by Tmborsikadu** [comment]
> **Severity**: Low, Medium, High, Critical
> **Priority**: 1, 2, 3, 4

ok, I will change it. Thank you
