### ISSUE TITLE
The link of “Turkish Airlines” doesn’t work in Romanian language

### ISSUE THREAD

**Issue by Tmborsikadu** [BragaAndrei/testing#87]
**Description:**  The link of “Turkish Airlines” doesn’t work
**Platform:** Windows 10 64 bit/ Chrome 70.0.3538.110
**Step to reproduce:**
1.	Go to website airport.md
2.	Click on ” Information for passengers”
3.	Scroll down
4.	Choose Romanian language
5.	Click on “Check in”
6.	Scroll down page
7.	Choose links of “Turkish Airlines”

**Actual result:**  When I click on this link, it shows me “Error 404”
**Expected result:**  It must be opened website of “Turkish Airlines”
**Severity**:  Critical
**Priority**: 2
**Screenshot attached (the defect):**
![image](https://user-images.githubusercontent.com/34817696/49836065-ff571e80-fda9-11e8-95ba-593a212f93ea.png)

**Comment by BragaAndrei** [comment]
Severity Critical!
