### ISSUE TITLE
Clear list is not working

### ISSUE THREAD

**Issue by zikus1** [BragaAndrei/testing#9]
1.Open ListBoxer
2.Select in field 'Range' and click "all"
3.In filed 'Symbols' check "Numeric"
4..In filed 'Symbols' check "Alphabetic"
5.Insert some data in field '1':"andrey"
6.Click on [Add to List] button
7.Click on [Clear List] button

Expected result: The program list deleted

Actual result: Is not active button [Clear List]

Priority:High
Severity:Critical

![bag 3](https://user-images.githubusercontent.com/43721390/46562748-56ea9100-c906-11e8-8937-6d8a9dee71d5.jpg)

**Comment by BragaAndrei** [comment]
It's great that you paid attention
