### ISSUE TITLE
The jumping pictures.

### ISSUE THREAD

**Issue by AlinaCilikov** [BragaAndrei/testing#91]
**Description:** When you click on [Homepage] or [Site map] button, the picture appear and immediately change to another.
Platform: Win10/ Opera/(Chrome Версия 54.0.2840.87 m)
**Step to reproduce:**
⦁	Open in browser the site http://www.airport.md/homepage-ro/
⦁	Click on on [Homepage] or [Site map] button .
⦁	See the picture witch appear after the click.
**Actual result:** 
The picture appeared and immediately changed to another.
Expected result: The picture appeared. 
**Severity:** Medium
**Priority:** 2
**Screenshot attached (the defect):**
![image](https://user-images.githubusercontent.com/45799866/49864160-81772f80-fe0a-11e8-9900-533cfc53a260.png)
![image](https://user-images.githubusercontent.com/45799866/49864184-90f67880-fe0a-11e8-93e3-20685e702949.png)

**Comment by BragaAndrei** [comment]
Perfect!!
