### ISSUE TITLE
The button Auction missing

### ISSUE THREAD

**Issue by AlinaCilikov** [BragaAndrei/testing#94]
**Description:** When the language is English and you click on   'Business Information ' "button" we see that the   'Auction' "button" missing. But if the language is Romanian or Russian the  'Auction' "button" is on the list.
**Platform:** Win 10/ Opera/(Chrome Версия 54.0.2840.87 m)
**Step to reproduce:**
⦁	Open in browser the site http://www.airport.md/homepage-ro/
⦁	Click on   'Business Information' "button".
**Actual result:** 
 When the language was English   the   'Auction' "button" was missing.
**Expected result:** The 'Auction' "button" was missing. 
**Severity:** Low
**Priority:** 3
**Screenshot attached (the defect):** 
![image](https://user-images.githubusercontent.com/45799866/49866884-a622d580-fe11-11e8-81ef-1649c8c44aa2.png)

**Comment by BragaAndrei** [comment]
I did not find this bug!
great work!
