### ISSUE TITLE
The Auction page is empty

### ISSUE THREAD

**Issue by AlinaCilikov** [BragaAndrei/testing#95]
**Description:** When the language is Romanian or Russian and you click on "Auction" we see that the page is empty.
**Platform:** Win 10/ Opera/(Chrome Версия 54.0.2840.87 m)
**Step to reproduce:**
⦁	Open in browser the site http://www.airport.md/homepage-ro/
⦁	Click  on 'Business Information' .
⦁	Click  on 'Auction'.
**Actual result:** 
The  Auction page was empty. Any information missed.  
**Expected result:** Information on Auction page appeared. 
**Severity:** Low
**Priority:** 3
**Screenshot attached (the defect):** 
![image](https://user-images.githubusercontent.com/45799866/49867751-09ae0280-fe14-11e8-9a52-282468d8383e.png)

**Comment by BragaAndrei** [comment]
Step to reproduce -Step**s** to reproduce: because you have more than one step

**Comment by BragaAndrei** [comment]
i checked it! good
